spring.application.name=Lumora

# --- Ket noi Postgres (container docker-compose) ---
spring.datasource.url=jdbc:postgresql://localhost:5434/lumora
spring.datasource.username=lumora
spring.datasource.password=lumora

# --- Hibernate/JPA ---
# update: tu dong tao/sua bang theo Entity khi chay (chi dung cho dev, KHONG dung o production)
spring.jpa.hibernate.ddl-auto=update
# In ra console cau SQL Hibernate sinh ra, giup debug va hoc cach JPA map Entity -> SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
